#!/usr/bin/env ruby
require 'yaml'
require 'pp'
require 'csv'
require 'pathname'
require 'uri'
require 'optparse'
require 'fileutils'

options = {}
cli = OptionParser.new do |parser|
  parser.on('-f', '--filename FILENAME', 'Yaml Swagger filename') do |f| Pathname.new f end
  parser.on('-o', '--output OUTPUT', 'Output directory') do |o| Pathname.new o end
  parser.on('-v', '--version VERSION', 'Open banking version e.g. fase 1, 2, 3') do |v| Pathname.new v end
end

cli.parse!(into: options)

version = options[:version]

oas = YAML.load_file(options[:filename])
output_path = options[:output].realpath.to_s + '/'

def get_file_data(file, section)

  if ("schemas".eql? section)
    upperLimit = /^  schemas:/
    lowerLimit = /^  parameters:/
  elsif ("parameters".eql? section)
    upperLimit = /^  parameters:/
    lowerLimit = /^  responses:/
  elsif ("responses".eql? section)
    upperLimit = /^  responses:/
    lowerLimit = /^  responses:/
  end

  sectionContent = ""
  isSection = false

  file.each do |line|
    if isSection
      sectionContent << line
    end
    if (line.downcase=~upperLimit)
      isSection = true
    elsif (line.downcase=~lowerLimit)
      isSection = false
    end
  end

  file.close

  return sectionContent
end

puts "> Starting analyse on " + options[:filename].to_s

url = oas['servers'][0]['url'].split("open-banking")[1]

filename = output_path + "_open_banking_fase"+version.to_s+"_apis_part.yml"

oas['paths'].each_with_index do |(path, methods)|

  printedPaths = Array.new

  methods.each_with_index do |(op, spec)|

    puts '─ ' + op.upcase + ' ' + path

    puts '  ├── Extracting fields from responses...'

    puts '  ├── Writing file ' + filename

    tempfile=File.open("file.tmp", 'w+:UTF-8')
    f=File.new(filename)

    f.each do |line|
      tempfile<<line

      fullUrl = (""+url+path);

      if (line.downcase=~/^paths:/ && (!printedPaths.include? fullUrl))
        tempfile << "  "+fullUrl+":"
        printedPaths.append(fullUrl)
        tempfile << methods.to_yaml.gsub!(/^/, '    ').split("---")[1]
      end
    end

    f.close
    tempfile.close
    
    FileUtils.mv("file.tmp", filename)

    puts "  └── Finished! \n\n"
  end
end

oas['components'].each_with_index do |(componentTitle, componentArray)|
  printedSchemas = Array.new
  printedParameters = Array.new
  printedResponses = Array.new

  puts '  ├── Writing file ' + filename

  tempfile=File.open("file.tmp", 'w+:UTF-8')

  fileSchemas = get_file_data(File.new(filename), "schemas")
  fileParameters = get_file_data(File.new(filename), "parameters")
  fileComponents = get_file_data(File.new(filename), "responses")

  f=File.new(filename)

  f.each do |line|
    tempfile<<line

    if (line.downcase=~/^  schemas:/ && ("schemas".eql? componentTitle))
      tempfile << "\n"
      oas['components']['schemas'].each_with_index do |(contentt, dataa)|
        if (!fileSchemas.include? contentt)
          tempfile << "    "+contentt+":"
          tempfile << dataa.to_yaml.gsub!(/^/, '      ').split("---")[1]
        end
      end
    elsif (line.downcase=~/^  parameters:/ && ("parameters".eql? componentTitle))
      tempfile << "\n"
      oas['components']['parameters'].each_with_index do |(contentt, dataa)|
        if (!fileParameters.include? contentt)
          tempfile << "    "+contentt+":"
          tempfile << dataa.to_yaml.gsub!(/^/, '      ').split("---")[1]
        end
      end
    elsif (line.downcase=~/^  responses:/ && ("responses".eql? componentTitle))
      tempfile << "\n"
      oas['components']['responses'].each_with_index do |(contentt, dataa)|
        if (!fileComponents.include? contentt)
          tempfile << "    "+contentt+":"
          tempfile << dataa.to_yaml.gsub!(/^/, '      ').split("---")[1]
        end
      end
    end
  end

  f.close
  tempfile.close
  
  FileUtils.mv("file.tmp", filename)

  puts "  └── Finished! \n\n"
  # end
end

puts '> Files generated!'

# exit 0